modLoader = "javafml"
loaderVersion = "[20,)"
license = "Apache-2.0"

[[mods]]
modId = "forgedfabricloader"
version = "${version}"
displayName = "ForgedFabricLoader"
displayURL="https://github.com/PortingLab/ForgedFabricLoader" #optional
logoFile="icon.png" #optional
credits="FabricMC" #optional
authors="PortingLab" #optional
description = '''
Re-implementation Fabric Loader API on Forge.
'''
